#:schema node_modules/wrangler/config-schema.json
name = "web"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-10-18"
pages_build_output_dir = "./build/client"

[placement]
mode = "smart"

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#d1-databases
[[d1_databases]]
binding = "DB"
database_name = "invoice002-db"
database_id = "895f3ccf-bb50-45ef-8e98-294b8e6a863a"
preview_database_id = "LOCAL-INVOICE-001-DB" # Required for Pages local development
migrations_dir = "migrations"

[vars]

[[env.production.d1_databases]]
binding = "DB"
database_name = "invoice002-db"
database_id = "895f3ccf-bb50-45ef-8e98-294b8e6a863a"
migrations_dir = "migrations"

[env.production.vars]
BETTER_AUTH_TRUSTED_ORIGINS = "https://tess-fs.pages.dev/"
BETTER_AUTH_URL = "https://tess-fs.pages.dev"